runtime: java17
instance_class: F1

liveness_check:
    path: "/health"
    check_interval_sec: 60
    timeout_sec: 4
    failure_threshold: 2
    success_threshold: 2

readiness_check:
    path: "/health"
    check_interval_sec: 10
    timeout_sec: 4
    failure_threshold: 2
    success_threshold: 2
    app_start_timeout_sec: 300
